# Generated by Django 2.2.5 on 2019-09-04 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0002_professor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
